name: Build and Deploy Code
on:
  push:
    branches: [main]
  pull_request: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: say hi to daniel
        run: echo "hi daniel"



